name: First Workflow
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome
        run: echo "welcome to first workflow!"
        
      - name: Checkout repo  
           uses:actions/checkout@v6-beta
        
      - name: List repositories  
        run: ls -la
